import os, sys
from sensor import utils
from sensor.exception import SensorException
from sensor.logger import logging
from sensor.entity import config_entity


class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainingArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...